### ISSUE TITLE
Scan device 

### ISSUE THREAD

**Issue by nneveu** [slaclab/lcls-tools#102]
**Is your feature request related to a problem? Please describe.**
We would like to be able to take any PV or set of PV's and scan them within epics limits. This may require adding the PV limits to yaml files.

**Describe the solution you'd like**
Create submodule, that can take lcls-tools devices/MAD names and device limits and scan within full range of user provided limits for device(s)

**Describe alternatives you've considered**
- Letting other applications write their own python scan functions individually. 
- Asking controls group to put this directly into the controls system.

**Additional context**
First application goals for this feature are quad scans.

**Comment by MattKing06** [comment]
Is this covered in #104 ?
