### ISSUE TITLE
Update generator to hide different image PVs

### ISSUE THREAD

**Issue by nneveu** [slaclab/lcls-tools#106]
**Is your feature request related to a problem? Please describe.**
Some cameras use :IMAGE or :ImageArrayData PVs. Currently we have to treat these differently when loading them in the screen class. 

**Describe the solution you'd like**
Update yaml generator class to deal with these differences and return the same key regardless of PV type.

**Describe alternatives you've considered**

- Dealing with the differences in the screen class.
- Not dealing with the differences at all.

**Additional context**
Nice to have, but not needed for initial screen class development.

**Comment by MattKing06** [comment]
Closed in #112
