### ISSUE TITLE
Make a Wire Scanner Device 

### ISSUE THREAD

**Issue by nneveu** [slaclab/lcls-tools#110]
**Is your feature request related to a problem? Please describe.**
We would like to make wire scanner (WS) objects similar to the magnet and screen objects in python.

**Describe the solution you'd like**
The WS object should be able to scan and record data from wire scanners listed in the YAML files.

**Describe alternatives you've considered**
Not being able to scan wires in python.

**Comment by kabanaty** [comment]
Closing with #176
