### ISSUE TITLE
Add Wire Scanners to yaml files

### ISSUE THREAD

**Issue by kabanaty** [slaclab/lcls-tools#170]
**Is your feature request related to a problem? Please describe.**
Add wire scanner devices and PVs to appropriate yaml files.

**Comment by nneveu** [comment]
@kabanaty a little info to help w/ this...

Please add an extract_wires function [here](https://github.com/slaclab/lcls-tools/blob/main/lcls_tools/common/devices/yaml/generate.py) to do this programmatically.

[This file](https://github.com/slaclab/lcls-tools/blob/main/lcls_tools/common/devices/yaml/lcls_elements.csv) should have the wire base names you need, but if not, we'll need to update it.
