### ISSUE TITLE
general magnet class

### ISSUE THREAD

**Issue by nneveu** [slaclab/lcls-tools#18]
Some pydm code references SC magnets. Need to generalize this:
https://github.com/slaclab/lcls-tools/blob/main/lcls_tools/common/pydm_tools/magnet.py

**Comment by nneveu** [comment]
Here too: 
https://github.com/slaclab/lcls-tools/blob/main/lcls_tools/common/pydm_tools/displayUtils.py

**Comment by MattKing06** [comment]
covered by #104 ?
