### ISSUE TITLE
Add Magnet Config/Data Files

### ISSUE THREAD

**Issue by MattKing06** [slaclab/lcls-tools#87]
### Is your feature request related to a problem? Please describe.
Currently access to PVs for magnets and other calibration/metadata information is done via the control room. It would be good to collate this information so it can be shared between applications/scripts that use lcls-tools.

### Describe the solution you'd like
A set of YAML config files should be created that contain the relevant information for a magnet.

### Describe alternatives you've considered
Copying the information from application to application is currently the way this is done.

### Additional context
This should be organised such that it can replicated for other components of the machine, i.e. Screens.

**Comment by nneveu** [comment]
Addressed in #94
