### ISSUE TITLE
Automatic yaml file generation 

### ISSUE THREAD

**Issue by nneveu** [slaclab/lcls-tools#92]
**Is your feature request related to a problem? Please describe.**
Diagnostic and element information is often scattered. It would be nice to have human readable files with control and meta data information in the same location.

**Describe the solution you'd like**
A script that can either grab elements directly from the oracle data base or a csv file and auto generate yaml files using information from the database. The files may need some hand tuning, but hopfully would have all elements of a certain type per area. i.e. all magnets in the GUNB area can be added to the gunb yaml file with some bare minimum information. 

**Describe alternatives you've considered**
Using another model, adding or grepping for PV's manually or case by case basis.

**Additional context**
We want to automate this, so that yaml files can be easily updated when changes are made to the database, or new elements installed.

**Comment by MattKing06** [comment]
closed by #101
