### ISSUE TITLE
Function to Retrieve Device List From Beampath

### ISSUE THREAD

**Issue by eloiseyang** [slaclab/lcls-tools#93]
**Is your feature request related to a problem? Please describe.**
Querying a subset of devices that lie along a selected beampath, such as  `CU_HXR` or `SU_SXR`, is a common software problem in AD software. Though a scientist may recover the beampath for a selected member device in MAD, or through the SLAC oral tradition, a programmer may find it challenging to include that configuration in their software. In fact, the most common solution to this problem to date is to hard code the accelerator configuration into a labeled list of devices. We have yet to create a permanent location where we may programmatically access and query devices along a selected beampath.

**Describe the solution you'd like**
We should write a single function for lcls-tools that takes one required input of a beampath string, and one optional input of a list of device types to additionally filter the results. It should output a list of the devices along the selected beampath in Z order. To make this query simpler, we should include the beampath as metadata in each device's YAML file when we generate them from the Oracle database.

**Comment by nneveu** [comment]
i.e. generate a magnet collection with all magnets in several areas (areas in the beam path)
